language: cpp
compiler:
  - gcc
before_install:
  - pip install --user cpp-coveralls
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq lcov curl
script:
  - mkdir build && cd build && cmake .. && make
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
