language: cpp
compiler:
  - gcc
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq curl
script:
  - mkdir build && cd build && cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug .. && make
